#!/bin/sh

export tabstop=4
export TERM=dumb
export SHELL="$PLAN9/bin/rc"
export acmeshell="$SHELL"
export PAGER=cat
export GIT_PAGER=$PAGER
export EDITOR=E

9 $PLAN9/bin/acme -f /mnt/font/LiberationMono/11a/font -F /mnt/font/LiberationMono/10a/font

