#!/usr/bin/sh

export tabstop=4
export TERM=dumb
export acmeshell="$PLAN9/bin/rc"
export SHELL="$PLAN9/bin/rc"
export GIT_PAGER=cat
export PAGER=cat
export EDITOR=E

9 $PLAN9/bin/acme -f /mnt/font/LiberationMono/11a/font -F /mnt/font/LiberationMono/10a/font

