#!/usr/bin/awk -f

# Copyright © 2018, Alexander Ben Nasrallah <me@abn.sh>
# Use of this source code is governed by a BSD 3-clause
# style license that can be found in the LICENSE file.

BEGIN {
	if (chars == "") {
		chars = "//"
	}
	if (ARGC > 1) {
		usage = sprintf("usage: %s [awk args] [-v chars=<chars (default: //)>] [-- -?]", "cmnt")
		print usage  > "/dev/stderr"
		print ""  > "/dev/stderr"
		print "Insert charactern at the beginning of each line." > "/dev/stderr"
		exit 1
	}
}

/^./ {
	sub("^.", chars " &")
	print
}

/^$/ {
	sub("^$", chars)
	print
}
