#!/usr/bin/awk -f

# Copyright © Alexander Ben Nasrallah 2018 <abn@posteo.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

BEGIN {
	if (chars == "") {
		chars = "//"
	}
	if (ARGC > 1) {
		usage = sprintf("usage: %s [awk args] [-v chars=<chars (default: //)>] [-- -?]", "cmnt")
		print usage  > "/dev/stderr"
		print ""  > "/dev/stderr"
		print "Insert charactern at the beginning of each line." > "/dev/stderr"
		exit 1
	}
}

/^./ {
	sub("^.", chars " &")
	print
}

/^$/ {
	sub("^$", chars)
	print
}
