#!/bin/sh

# Copyright © 2018, Alexander Ben Nasrallah <me@abn.sh>
# Use of this source code is governed by a BSD 3-clause
# style license that can be found in the LICENSE file.

chars=${1:-//}

awk -v chars=$chars '
/^./ {
	sub("^.", chars " &")
	print
}

/^$/ {
	sub("^$", chars)
	print
}
'
