#!/bin/sh
# Tcl ignores the next line -*- tcl -*- \
exec /usr/local/bin/wish8.5 "$0" -- "$@"

# Copyright © 2018, Alexander Ben Nasrallah <me@abn.sh>
# Use of this source code is governed by a BSD 3-clause
# style license that can be found in the LICENSE file.

# TODO
# hotkeys for
# e: open current file in editor (use plumb)
# f,b: forwards backwards
# /,?: search forward backward
#
# select text to plumb
# evaluate $tabstop
# get font from args

package require Tk

wm title . "less"

grid [ttk::frame .container -padding "0 0 0 0"] -column 0 -row 0 -sticky nwes
grid columnconfigure . 0 -weight 1
grid rowconfigure . 0 -weight 1

grid [tk::text .container.content -width 10 -height 10 -font {{Liberation Mono} 12}] -column 0 -row 0 -sticky nwes
grid columnconfigure .container 0 -weight 1
grid rowconfigure .container 0 -weight 1

if { $argc > 0 } {
	set file [lindex $argv 0]
	wm title . $file
} else {
	set file "/dev/stdin"
}

set input [open $file]

.container.content insert 1.0 [read $input]

if {[catch {close $input} err]} {
	puts "Something went wrong"
}
