#!/bin/sh

if [ $# -lt 3 ] ; then
	echo "usage <project name> <ssh user name> <server addres> [port]"
	exit 1
fi

PROJECT=$1
USER=$2
SERVER=$3
GITDIR=git
PROJECTDIR=$GITDIR/$PROJECT.git
if test -z $4; then
	PORT=22
else
	PORT=$4
fi

ssh -p $PORT -l $USER $SERVER "mkdir -p $PROJECTDIR && cd $PROJECTDIR && git init --bare"
