#!/bin/sh

EDITOR=${EDITOR:-vim}
PAGER=${PAGER:-more}

if [ -d "$1" ]
then
	cd "$1"
	$SHELL
	exit 0
fi

if [ -f "$1" ]
then
	$EDITOR "$@"
	exit 0
fi

if (echo "$1" | grep -qE '(https?|file)://.+')
then
	chromium "$1"
	exit 0
fi

# git commits
if (echo "$1" | grep -qE '[a-f0-9]{7}')
then
	git show "$1" | $PAGER
	exit 0
fi
