#!/usr/bin/awk -f

# Copyright © 2018, Alexander Ben Nasrallah <me@abn.sh>
# Use of this source code is governed by a BSD 3-clause
# style license that can be found in the LICENSE file.

BEGIN {
	if (ARGC > 1) {
		print "Removes the first non-blank word and an optional following blank of each line."
		exit 1
	}
}

{
	sub("^[^[:blank:]]*[[:blank:]]?","")
	print
}
